local hola1 = 3;
global hola = hola1;
local hola2 = 3;
local hola3 = "adios"^2;
hola5 = uppercase(hola3^2);
println(hola);
println(hola1);
println(hola2);
println(uppercase(hola3^2));
println(lowercase(hola5));
